name: 'Set up Node.js'
description: 'Install Node.js and development dependencies'

inputs:
  node-version:
    description: 'Node.js version to install'
    default: '18'

  registry-url:
    description: 'Registry URL (required for publish)'
    required: false

runs:
  using: 'composite'
  steps:
    - name: 'Install pnpm'
      uses: pnpm/action-setup@c3b53f6a16e57305370b4ae5a540c2077a1d50dd

    - name: 'Install Node.js'
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
        registry-url: ${{ inputs.registry-url }}
        cache: pnpm

    - name: 'Install development dependencies'
      shell: bash
      run: pnpm install --frozen-lockfile
