name: 'Set up Node.js'
description: 'Install Node.js and development dependencies'

inputs:
  node-version:
    description: 'Node.js version to install'
    default: '22'

  registry-url:
    description: 'Registry URL to set'
    required: false

  install-dependencies:
    description: 'Run pnpm install to install dependencies'
    type: boolean
    default: true

runs:
  using: 'composite'
  steps:
    - name: 'Install pnpm'
      uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0

    - name: 'Install Node.js ${{ inputs.node-version }}'
      uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
      with:
        node-version: ${{ inputs.node-version }}
        registry-url: ${{ inputs.registry-url }}
        cache: pnpm

    - name: 'Install dependencies'
      if: ${{ inputs.install-dependencies == 'true' }}
      shell: bash
      run: pnpm install
