name: 'Set up Node.js'
description: 'Install Node.js and development dependencies'

inputs:
  node-version:
    description: 'Node.js version to install'
    default: '20'

  registry-url:
    description: 'Registry URL to set'
    required: false

  install-dependencies:
    description: 'Run pnpm install to install dependencies'
    type: boolean
    default: true

runs:
  using: 'composite'
  steps:
    - name: 'Install pnpm'
      uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # v4.0.0

    - name: 'Install Node.js ${{ inputs.node-version }}'
      uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.3
      with:
        node-version: ${{ inputs.node-version }}
        registry-url: ${{ inputs.registry-url }}
        cache: pnpm

    - name: 'Install dependencies'
      if: ${{ inputs.install-dependencies == 'true' }}
      shell: bash
      run: pnpm install
