name: 'Publish to NPM'
description: 'Publish a package to NPM'

inputs:
  package:
    description: 'Path to package'
    required: true

  token:
    description: 'NPM auth token'
    required: true

runs:
  using: 'composite'
  steps:
    - id: publish
      name: Publish package
      uses: JS-DevTools/npm-publish@0be441d808570461daedc3fb178405dbcac54de0
      with:
        package: ${{ inputs.package }}
        token: ${{ inputs.token }}

    - if: ${{ steps.publish.outputs.id }}
      name: Tag commit
      shell: bash
      env:
        TAG_NAME: ${{ steps.publish.outputs.id }}
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git tag -a "${TAG_NAME}" -m "${TAG_NAME}"
        git push origin "${TAG_NAME}"
