name: Continuous integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: 'Install 🔧'
        uses: ./.github/actions/setup

      - name: 'Run checks ✅'
        run: pnpm run all

  publish:
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    needs: [check]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: 'Install 🔧'
        uses: ./.github/actions/setup
        with:
          registry-url: https://registry.npmjs.org/

      - name: 'Build 🏗️'
        run: pnpm run build

      - name: 'Publish 🚀'
        run: pnpm publish --recursive
