name: Pull Request Checks

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: 'Install 🔧'
        uses: ./.github/actions/setup

      - name: 'Run checks ✅'
        run: pnpm run all
